name: "Deploy para hostgator"
on: 
    push:
        branches:
            - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
    - name: Install npm dependencies
      run: npm install

    - name: Set up environment variables
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env.local
        echo "VITE_EVENTO_UUID=${{ secrets.VITE_EVENTO_UUID }}" >> .env.local

    - name: Run build task
      run: npm run build --if-present


    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete -vv"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
